DOMAIN = "vigobus"
SERVICE_REFRESH = "refresh"

PARADAS_URL = "https://datos.vigo.org/data/transporte/paradas.json"

ESTIMACION_URL = (
    "https://datos.vigo.org/vci_api_app/api2.jsp"
    "?tipo=TRANSPORTE-ESTIMACION-PARADA&id={}"
)
AVISOS_URL = "https://datos.vigo.org/vci_api_app/api2.jsp?tipo={}"
AVISOS_LINEAS_URL = "https://datos.vigo.org/vci_api_app/api2.jsp?tipo=WEBPUB_AVISOS_TRANSPORTE&lang={}"

SCAN_INTERVAL = 30
DEFAULT_SCAN_INTERVAL = 30
MIN_SCAN_INTERVAL = 15
MAX_SCAN_INTERVAL = 300

DEFAULT_NEAREST_RECALC_DISTANCE_M = 120
MIN_NEAREST_RECALC_DISTANCE_M = 20
MAX_NEAREST_RECALC_DISTANCE_M = 1000

DEFAULT_NOTIFY_ENABLED = False
DEFAULT_NOTIFY_MINUTES = 5
MIN_NOTIFY_MINUTES = 1
MAX_NOTIFY_MINUTES = 60

DEFAULT_NOTIFY_COOLDOWN_MIN = 20
MIN_NOTIFY_COOLDOWN_MIN = 1
MAX_NOTIFY_COOLDOWN_MIN = 240

DEFAULT_ALERTS_LANG = "es"
DEFAULT_ALERTS_MAX_PER_STOP = 10
MIN_ALERTS_MAX_PER_STOP = 1
MAX_ALERTS_MAX_PER_STOP = 25
